config/routes.rb
Rails.application.routes.draw do
  resources :pet_guess
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet_guess.rb
class PetGuess < ApplicationRecord
  def set_guess_strategy(strategy)
    @guess_strategy = strategy
  end

  def pet_type_guess
    return nil if @guess_strategy.nil?
    @pet_type_guess = @guess_strategy.make_pet_type_guess(@height, @weight)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pet_guess_controller.rb
class PetGuessController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pet_guess_helper.rb
module PetGuessHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetTypePredictor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pet_guess/index.html.erb
<h1>This is a best Pet Guesser. It will guess whether you are a Cat Person or a Dog Person based on your height and weight!</h1>

<%= link_to 'Let Us Guess Your Pet-Type', new_pet_guess_path %>

app/views/pet_guess/new.html.erb
<%= form_for :pet_guess do |f| %>
  Height(inches): <%= f.text_field :height %><br />
  Weight(lbs): <%= f.text_field :weight %><br />
  <%= f.submit %>
<% end %>